# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 08:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xmsc', '0003_phone_small_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 12, 20, 8, 11, 49, 205907, tzinfo=utc), verbose_name='评论时间')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xmsc.Phone', verbose_name='手机型号')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '手机评论',
                'verbose_name_plural': '手机评论',
            },
        ),
    ]
