# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 03:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 3, 19, 52, 292237, tzinfo=utc), verbose_name='评论时间'),
        ),
    ]
