# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import xmsc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '手机分类',
                'verbose_name_plural': '手机分类',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('img', models.ImageField(blank=True, upload_to=xmsc.models.upload_image)),
                ('kind', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmsc.Category', verbose_name='分类')),
            ],
        ),
    ]
