# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import xmsc.models


class Migration(migrations.Migration):

    dependencies = [
        ('xmsc', '0002_auto_20181219_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='small_img',
            field=models.ImageField(blank=True, upload_to=xmsc.models.upload_image),
        ),
    ]
